### ISSUE TITLE
Can end up appearing to be alone in a room

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1262] opened 2023-07-14 17:28 UTC
### Steps to reproduce

Under some circumstances, it seems its possible to get into a state where it looks like you're the only one in a room, when that's not the case. I managed to trigger this my sleeping the laptop and then waking it up, leaving EC open. I think it's also possible to get into this state on internet connection issues, probably when the livekit peer connection drops?

### Will you send logs?

Yes

**Comment by fkwp** [comment] 2023-07-19 13:59
duplicate of https://github.com/vector-im/element-call/issues/1268

**Closed as completed by fkwp** 2023-07-19 13:59 UTC
Labels: T-Defect
