### ISSUE TITLE
Display name changed to `[👻]`

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-call#1241] opened 2023-07-12 07:33 UTC
### Steps to reproduce

1. Using Element Call for our daily standup
2. Someone logged in

#### What did you expect?

To see their normal display name

#### What happened instead?

Over the past couple of days i've noticed two different people with their display name that had been changed to `[👻]`. 
When asking that person about their display name, they said they had not changed it.

### Will you send logs?

No

**Comment by robintown** [comment] 2023-07-12 18:19
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3598 (this was happening due to rate limits caused by a bug in the js-sdk which that PR fixes)

**Closed as completed by robintown** 2023-07-12 18:19 UTC
Labels: T-Defect
