### ISSUE TITLE
Fullscreening a feed mutes all other feeds

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-call#510] opened 2022-08-11 13:15 UTC
We should route audio through separate media elements so that it doesn't stop working when video feeds are hidden

**Comment by robintown** [comment] 2022-08-11 13:25
Duplicate of https://github.com/vector-im/element-call/issues/509

**Closed by robintown** 2022-08-11 13:25 UTC
Labels: T-Defect, S-Critical, O-Occasional

**Comment by SimonBrandner** [comment] 2022-08-11 13:26
Ah, you beat me to it :D
