### ISSUE TITLE
Screen sharing: Full screen will cause the screen to display abnormally.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-call#594] opened 2022-09-22 02:48 UTC
### Steps to reproduce

1. Join a video room and start a video call;
2. **Select the screen where Element-Web is located** to start screen sharing;
3. Set the screen sharing screen to full screen, make sure that the screen where the full screen screen is located and the screen where Element-Web is located are the same.

#### What did you expect?
n/a
#### What happened instead?
As shown in the figure, abnormal patterns such as color spots appear on the screen after full screen.
![{1CD66A16-C7C3-1502-8161-13B988083262}](https://user-images.githubusercontent.com/48104960/191646733-58f7940c-eeba-4065-9c13-4ae0809f0280.png)

### Operating system

x64 Windows 10 21H2 LTSC

### Browser information

Catsxp Browser 2.9.3 (based on Chromium 105.0.5195.118 for Windows x64)

### URL for webapp

0.2.13 (Element-web version: d1754559ad2b-react-fa2ec7f6c98e-js-2e10b6065cca)

### Will you send logs?

No

**Comment by robintown** [comment] 2022-09-22 02:56
Duplicate of https://github.com/vector-im/element-call/issues/555

**Closed by robintown** 2022-09-22 02:56 UTC
Labels: T-Defect
