### ISSUE TITLE
Audio cooldown is too short in spotlight

### ISSUE THREAD

**Issue by hanthor** [vector-im/element-call#1702] opened 2023-10-05 15:14 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
 A participant that has no video but audio will go to the top of the stack while talking but will drop back down instantly

In a room with 12 participants and a screenshare

#### What did you expect?

There should be a 3-5 second cooldown on placing an unmuted talking participant to the top posiotiong

### Operating system

macOS

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment] 2023-10-05 16:33
Duplicate of https://github.com/vector-im/element-call/issues/1222

**Closed as not planned by robintown** 2023-10-05 16:33 UTC
Labels: T-Defect
