### ISSUE TITLE
Highlight borders cropped when scrollbar visible and scrolled to top of screen

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-call#1585] opened 2023-09-25 10:31 UTC
### Steps to reproduce

1. In the weekly call
2. Scrolled down then back up
3. Noticed green highlight missing top edge when rick was speaking. Also applies to white mouseover highlight.

Took this screenshot when mouseover was going as that was easiest to replicate, and it crops on the side and the top - juho here was the top left tile.

![cropped](https://github.com/vector-im/element-call/assets/1917473/e5eae75c-e34a-4907-8450-73c6c5da93c2)

#### What did you expect?
Complete surround of speaking/highlight notification

#### What happened instead?
Cropped off

### Operating system

linux

### Browser information

Google Chome Version 116.0.5845.187 (Official Build) (64-bit)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by anoadragon453** [comment] 2023-09-25 10:34
Duplicate of https://github.com/vector-im/element-call/issues/1584 (sorry :)

**Closed as not planned** 2023-09-25 16:59 UTC
Labels: T-Defect
