### ISSUE TITLE
Typing in rageshake dialog triggers mute shortcuts

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#839] opened 2023-01-12 13:22 UTC
### Steps to reproduce

1. Open rageshake window
2. Type a rageshake description using the letters 'm' and 'v'

#### What did you expect?
Mute state to not change

#### What happened instead?
Mute start changed

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2023-01-13 05:50
Duplicate of https://github.com/vector-im/element-call/issues/771

**Closed by SimonBrandner** 2023-01-13 05:50 UTC
Labels: T-Defect
