### ISSUE TITLE
Element Call: Automatic Gain Control

### ISSUE THREAD

**Issue by Ceiridge** [vector-im/element-call#2707] opened 2024-10-31 21:32 UTC
#### What would you like to do?

Be able to disable AGC (Automatic Gain Control) in the native Element calls.

#### Why would you like to do it?

AGC heavily interferes with my audio volume, which makes it hard to be heard.

#### How would you like to achieve it?

A checkbox in the audio settings

### Have you considered any alternatives?

No.
Related **outdated** issue: https://github.com/element-hq/element-web/issues/6278

### Additional context

AGC refers to the _autoGainControl_ option, as seen here: https://stackoverflow.com/questions/37326846/disabling-auto-gain-conctrol-with-webrtc-app#:~:text=You%20can%20turn%20off%20audio%20processing%20using%20constraints

Adding checkboxes for the other options would also be a feature idea.

**Comment by bblacher** [comment] 2024-11-04 15:19
Duplicate of https://github.com/element-hq/element-call/issues/248

**Closed as not planned** 2024-11-04 15:19 UTC
Labels: T-Enhancement
