### ISSUE TITLE
Aspect ratio incorrect for video tiles after sender mutes & unmutes

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#962] opened 2023-03-17 15:00 UTC
### Steps to reproduce

1. Join call from two places, Alice & bob, both with video unmuted
2. Mute Alice's video
3. Unmuted Alice's video
4. Alice now appears in the wrong aspect ratio on Bob's screen.
5. Resize window horizontally on Bob's screen
6. Alice is now the right shape again

It looks like the object-fit CSS is not being correctly applied to crop the video to the right aspect ratio for the tile after the feed is unmuted. Causing the tile to change width fixes it.

### Browser information

This is specific to Chrome

### Will you send logs?

No

**Comment by robintown** [comment] 2023-05-12 14:16
I'm going to call this fixed by Chrome until proven otherwise, because no one in our stand-ups has seen this happen recently, and my timeboxed efforts to reproduce it didn't yield any results

**Closed by robintown** 2023-05-12 14:16 UTC
Labels: T-Defect, S-Minor, O-Occasional, Z-Platform-Specific

**Comment by alariej** [comment] 2023-05-13 07:47
Hi, I see a similar behavior when using Element Call in Quadrix on iOS:

1. Launch a videoconference (with no other participant)
2. Mute microphone
3. Unmute microphone
4. Mute video
5. Unmute video

The video stream gets zoomed in. This happens with both the native app (which uses Element Call in WKWebView) and the web app (running in Safari).

I notice a slight video stream break just after unmuting the microphone, as if the video stream changed track. Not sure if this is what causes a component to lose its styling parameters.

This does not seem to happen with the Android app.
