### ISSUE TITLE
Meeting Notes Feature

### ISSUE THREAD

**Issue by du64** [vector-im/element-call#913] opened 2023-02-14 14:15 UTC
#### What would you like to do?
Add a regular Matrix room behind a "meeting notes" feature that lets users write down things that happen during the call, such as directions or passwords.

#### Why would you like to do it?
Right now it's difficult to share information (links, images, passwords, etc..) during a call. 

#### How would you like to achieve it?
During the call users can share information in the "meeting notes" room, and at the end it prompts you to save the room data locally for future reference. Then it deletes the room data from the server.

### Have you considered any alternatives?

Most people will use Element call inside of Element, so the meeting notes feature should not be available unless it's just a video room.

**Comment by jakewb-b** [comment] 2023-03-01 14:47
I think this request will be covered by in-call chat, which we are working on, as well as future enhancements to collaboration such as whiteboarding and shared live documents. Closing this as a duplicate of those items.

https://github.com/vector-im/voip-internal/issues/110
https://github.com/vector-im/voip-internal/issues/25

**Closed by jakewb-b** 2023-03-01 14:47 UTC
Labels: T-Enhancement
