### ISSUE TITLE
Load the new call when you paste a new call URL on top of the old call URL and press enter

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-call#1900] opened 2023-11-16 09:38 UTC
#### What would you like to do?
I mostly reuse the same tab for Element Call calls - when I paste a new URL on top of the old one and press Enter, nothing happens on the first go (I have to press Enter again, or click refresh).

#### Why would you like to do it?
Remove one microstumble in daily use of EC.

#### How would you like to achieve it?
Detect when the stuff after the # changes in the URL and react to it.

**Comment by dbkr** [comment] 2023-11-17 11:05
Dupe of https://github.com/vector-im/element-call/issues/1873

**Closed as completed by dbkr** 2023-11-17 11:05 UTC
Labels: T-Enhancement
