### ISSUE TITLE
Fullscreen button is missing on 1:1 calls

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#617] opened 2022-10-11 13:07 UTC
### Steps to reproduce

1. Do a 1:1 call in EC
2. Try to go fullscreen
3. Discover there is no fullscreen button for no good reason

### Outcome

Add button.

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-10-11 13:37
Duplicate of https://github.com/vector-im/element-call/issues/566

**Closed by SimonBrandner** 2022-10-11 13:37 UTC
Labels: T-Defect
