### ISSUE TITLE
Camera light is on even when camera is off

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-call#684] opened 2022-10-30 10:57 UTC
### Steps to reproduce

1. Join a call with camera off

#### What did you expect?
Laptop webcam light is off

#### What happened instead?
Laptop webcam light is on, making me feel like the video is being received by the webapp :(

### Browser information

Chromium 106.0.5249.119 (Official Build) Arch Linux (64-bit)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment] 2022-10-30 11:12
Duplicate of https://github.com/vector-im/element-call/issues/195

**Closed by SimonBrandner** 2022-10-30 11:12 UTC
Labels: T-Defect

**Comment by robintown** [comment] 2022-10-30 20:34
@SimonBrandner That issue is closed, though?

**Comment by SimonBrandner** [comment] 2022-10-31 05:40
> @SimonBrandner That issue is closed, though?

It's closed because it's caused by an upstream Chromium issue, so there really isn't much we can do here
