### ISSUE TITLE
"Pop out this video" hoverover text is reversed in "Join call now" screen

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-call#498] opened 2022-08-04 10:58 UTC
### Steps to reproduce

1. Open a call screen (eg https://call.element.io/room/#testtestest:call.ems.host). It shows a preview of my video.
2. Hover over video
3. Observe backwards text

#### What did you expect?
Text in the right direction!

#### What happened instead?
![image](https://user-images.githubusercontent.com/1389908/182830401-cdee5f3b-9bfc-4a73-bd3d-159711231846.png)

### Operating system

Ubuntu 22.04

### Browser information

Firefox 103.0

### URL for webapp

https://call.element.io

### Will you send logs?

No

**Comment by robintown** [comment] 2022-08-04 13:30
Duplicate of https://github.com/vector-im/element-call/issues/392

**Closed by robintown** 2022-08-04 13:30 UTC
Labels: T-Defect, S-Minor, O-Occasional
