### ISSUE TITLE
Request for built tarballs similar to Element

### ISSUE THREAD

**Issue by wahjava** [vector-im/element-call#2160] opened 2024-02-07 09:11 UTC
#### What would you like to do?

I would like to make a request for pre-built tarballs that one could just extract in web server's document root, and get going.

#### Why would you like to do it?

It would make packaging/deployment of this service easier.

#### How would you like to achieve it?

Some kind of automation (perhaps github-actions?) to upload the built tarballs as the release artifact.

Thanks!

**Comment by spaetz** [comment] 2024-04-19 11:05
Duplicate of https://github.com/element-hq/element-call/issues/1876

**Closed as not planned** 2024-04-20 08:30 UTC
Labels: T-Enhancement
