### ISSUE TITLE
EC gets very confused by strangely formatted URLs

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1313] opened 2023-07-27 10:29 UTC
### Steps to reproduce

 1. Visit https://call.element.io/room/#?roomId=somestring
 2. Enter your name if prompted
 3. EC crashes with 'cannot read length of null'

No, we have no idea where this format of URL came from, but EC should either work or ignore the URL param entirely, not crash.

#### What did you expect?
Probably for it to ignore this weird URL.

#### What happened instead?
Crash

### Will you send logs?

No

**Comment by robintown** [comment] 2023-07-28 15:40
Duplicate of https://github.com/vector-im/element-call/issues/1300

**Comment by robintown** [comment] 2023-07-28 15:41
oh, well "EC should either work or ignore the URL param entirely, not crash" is a new point - I closed #1300 with the assumption that not generating those kinds of broken links is sufficient as a solution

**Closed as completed** 2023-08-01 16:44 UTC
Labels: T-Defect
