### ISSUE TITLE
InvalidKey: Decryption failed error when joining call on Element Web in Chrome

### ISSUE THREAD

**Issue by dylanirlbeck** [vector-im/element-call#2420] opened 2024-06-10 17:57 UTC
### Steps to reproduce

1. Join a call in Element Web via Chrome. ([Example call, in my case](https://call.element.io/room/#/soghoianchat?roomId=!TRQmEiBNtIIMZjvOUR:call.ems.host&password=-IOWMsv9Mi6xh%2Bci9mKgbw).)
2. Join the call in Firefox, and see the issue resolved.

#### What did you expect?

To see the video of other participants and hear their audio.

#### What happened instead?

I was able to see participant boxes, mute and unmute, and the appearance of a bar underneath a participant box that indicates whether they are speaking. But I was unable to see video or hear audio content.

Chrome developer logs were giving a continuous stream of `InvalidKey: Decryption failed:` errors.

Joining on Firefox appeared to resolve the issue.

Possibly related to https://github.com/element-hq/element-call/issues/2396 or https://github.com/element-hq/element-call/issues/2415, to the extent that the observed outcome was the same.

### Operating system

Windows

### Browser information

Google Chrome 125.0.6422.142

### URL for webapp

https://call.element.io/room/#/soghoianchat?roomId=!TRQmEiBNtIIMZjvOUR:call.ems.host&password=-IOWMsv9Mi6xh%2Bci9mKgbw

### Will you send logs?

No

**Comment by fkwp** [comment] 2024-06-18 13:32
duplicate of https://github.com/element-hq/element-call/issues/2429

**Closed as not planned by fkwp** 2024-06-18 13:32 UTC
Labels: T-Defect
