### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#277] opened 2022-03-18 11:45 UTC
Particularly for screenshares, i'm really missing not being able to make the focused video occupy maximum real estate.

This is particularly true on mobile, where you end up with layouts like this:

![image](https://user-images.githubusercontent.com/1294269/158997486-cfdd4254-54a8-4563-a0bc-967492ca7e34.png)

**Comment by dbkr** [comment] 2022-04-21 10:09
Dup of #179 I think? (or maybe #273)

**Comment by SimonBrandner** [comment] 2022-07-16 08:35
Duplicate of https://github.com/vector-im/element-call/issues/179

**Closed by SimonBrandner** 2022-07-16 08:35 UTC
Labels: T-Enhancement, X-Needs-Design, X-Needs-Product
