### ISSUE TITLE
Change ring sound

### ISSUE THREAD

**Issue by Commandcracker** [vector-im/element-call#1139] opened 2023-06-23 19:41 UTC
#### What would you like to do?

I would like to change the ring sound.

#### Why would you like to do it?

I would like to do it because I don't like the default sound.

#### How would you like to achieve it?

I would like to have some setting under Voice and Video to change the ring sound.

### Have you considered any alternatives?

Change the default ring tone to something that is not hurting my ears. 😃

### Additional context

It might also be nice to have different sounds per user, but this would probably need a protocol change.

**Comment by robintown** [comment] 2023-06-23 19:44
Duplicate of https://github.com/vector-im/element-web/issues/5891

**Closed by robintown** 2023-06-23 19:44 UTC
Labels: T-Enhancement
