### ISSUE TITLE
Join call display name field can trigger Google Pay

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-call#496] opened 2022-08-02 18:40 UTC
### Steps to reproduce

1. Click on a link to a call
2. Click on the Display Name field

#### What did you expect?

Not google pay

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/182449371-c6715787-e38d-40fa-b5bf-67649105c8ca.png)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment] 2022-08-02 20:07
Duplicate of https://github.com/vector-im/element-call/issues/384

**Closed by robintown** 2022-08-02 20:07 UTC
Labels: T-Defect
