### ISSUE TITLE
Element call should not kill webRTC connection if the mobile browser is put into background (or the phone in standby)

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#1318] opened 2023-08-01 11:50 UTC
#### What would you like to do?
Use Element call while the phone is in standby.
#### Why would you like to do it?
To providing a good phone call experience on element X is also should be possible to have the phone standby and participate in a call.
#### How would you like to achieve it?
Jitsy somehow manages to stay alive even if the phoen is in standby. So this seems to be solvable on th elemetn call side. Maybe they are using the [Web Audio API](https://stackoverflow.com/questions/40363606/how-to-keep-webrtc-datachannel-open-in-phone-browser-inactive-tab)

## Current situation:
Running a call in the background seems to work **but is unreliable**.
On Android Chrome and Android Firefox It works (in standby and if the browser is put into background) for about 5min and than is getting killed.
On the [element call wrapper experiment](https://github.com/pixlwave/Element-Call-macOS/tree/background-ios) it does not work with element call but it works with jitsy.

This needs more investigation!

**Comment by toger5** [comment] 2023-08-01 12:07
A theory that could be checked is, if no audio is sent (elemetn call mutes the tracks if there it did not detect someone speaking) the app gets killed/ended. Maybe element call happens to have a more agressive cutoff compared to jitsy and that is why it lives shorter compared to jitsy?
Maybe enforcing that there is always audio through the audio api makes the app stay alive?

**Comment by fkwp** [comment] 2023-09-14 09:35
a duplicate of https://github.com/vector-im/element-call/issues/1411

**Closed as completed by fkwp** 2023-09-14 09:35 UTC
Labels: T-Enhancement, X-Needs-Investigation
