### ISSUE TITLE
Opening a new Element Call tab should not boot you out of your current call

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-call#2314] opened 2024-04-16 13:58 UTC
### Steps to reproduce

- Join a call
- Click the call link again to open it in a new tab

#### What happened?

I was in a call, then accidentally clicked the call link again, opening the call pre-join screen in a new browser tab and this immediately booted me out of the call I was already in.

Error message:

> Error
This application has been opened in another tab.

#### What did you expect?

The new tab to not boot me out of the already connected tab. Element Web asks you this on the NEW instance if you open the same instance twice:

> Element is open in another window. Click "Continue" to use Element here and disconnect the other window.
Continue

### Operating system

Fedora 39

### Browser information

Firefox 124.0.2

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by bblacher** [comment] 2024-04-16 15:12
Duplicate of https://github.com/element-hq/element-call/issues/2283

**Comment by toger5** [comment] 2024-04-17 09:48
Thanks for the report. I agree that this is a duplicate. Closing this one in favor of https://github.com/element-hq/element-call/issues/2283

**Closed as completed by toger5** 2024-04-17 09:48 UTC
Labels: T-Defect
